model:
  fuser:
  
  calico:
    lidar_projector:
      type: CNNProjector
      channels: [256, 128, 64]
      kernel_size: 3
      stride: 1
    camera_projector:
      type: CNNProjector    
      channels: [80, 128, 64]
      kernel_size: 3
      stride: 1

    loss:
      type: ClipLoss
      # batch_loss: [True,2]
      # local_loss: True
      
    roi_align:
      spatial_scale: 0.125
      output_size: 7
      sampling_ratio: 2

data:
  samples_per_gpu: 1
  # train:
  #     dataset:
  #       ann_file: ${dataset_root + "nuscenes_infos_train_0.05.pkl"}

optimizer:
  type: AdamW
  lr: 1.0e-4
  weight_decay: 0.01


load_from: "pretrained/bevfusion-det.pth"